models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class User (UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)
    password = db.Column(db.String)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'username': self.username,            
            'password': self.password
        }


class Notice (db.Model):
    __tablename__ = 'notice'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    image = db.Column(db.Text)
    subtitle = db.Column(db.Text)
    text = db.Column(db.Text)
    date = db.Column(db.Date)
    id_user = db.Column(db.Integer, db.ForeignKey("user.id"))    

    @property
    def serialize(self):
        return {
            'id': self.id,
            'title': self.title,            
            'image': self.image,
            'subtitle': self.subtitle,
            'text': self.text,
            'date': self.date,
            'id_user': self.id_user
        }

class Commentary (db.Model):
    __tablename__ = 'commentary'
    id = db.Column(db.Integer, primary_key=True)    
    content = db.Column(db.Text)    
    date = db.Column(db.Date)
    id_user = db.Column(db.Integer, db.ForeignKey("user.id"))
    id_notice = db.Column(db.Integer, db.ForeignKey("user.id"))

    @property
    def serialize(self):
        return {
            'id': self.id,
            'content': self.title,                        
            'date': self.date,
            'id_user': self.id_user,
            'id_notice': self.id_notice
        }

app.py
from flask import Flask, render_template
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_login import LoginManager, current_user
from models import User, Notice

app = Flask(__name__)
app.config.from_object(Config)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy()
db.init_app(app)
migrate = Migrate(app, db)


login_manager = LoginManager()
login_manager.login_view = 'login'
login_manager.init_app(app)

from routes.user_bp import user_bp
from routes.notice_bp import notice_bp

app.register_blueprint(user_bp, url_prefix='/users')
app.register_blueprint(notice_bp, url_prefix='/notice')

@login_manager.user_loader
def load_user(user_id):
    # since the user_id is just the primary key of our user table, use it in the query for the user
    return User.query.get(int(user_id))


@app.route('/')
def index():
    ESCRITORES = ["alana", "dyogo", "jefferson", "nikoly", "jimenez", "deivid"]
    try:
        username = current_user.username
        user = {"username": username, "writer": username in ESCRITORES, 'id': current_user.id}
    except:
        user = ''

    notices = Notice.query.all()
    object = {
        "user": user,
        "notices": notices
    }
    return render_template("index.html", object=object)    

@app.route("/login/")
def login():
    return render_template("login.html")

if __name__ == '__main__':    
    app.run(debub=True)

controllers/NoticeController.py
import sys
from flask import render_template, redirect, url_for, request, abort, Flask
from models import Notice, User
from flask_login import login_user, login_required, current_user, logout_user
app = Flask(__name__)
app.config.from_object(Config)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
from flask_sqlalchemy import SQLAlchemy
from datetime import date
ESCRITORES = ["alana", "dyogo", "jefferson", "nikoly", "jimenez", "deivid"]

db = SQLAlchemy(app)

@login_required
def store():    
    if request.method == 'POST':

        form = request.form
        title = form['title']
        subtitle = form['subtitle']      
        text = form['text']      
        image = form['image']      
        idUser = User.query.filter_by(username=current_user.username).first().id
        data = date.today()
        
        notice = Notice(title=title, subtitle=subtitle, text=text, image=image, id_user=idUser, date=data)

        db.session.add(notice)
        db.session.commit()    
        return redirect(url_for('index'))
    else:                
        username = current_user.username
        user = {"username": username, "writer": username in ESCRITORES}
        return render_template('create_notice.html', user = user)

def show(notice_id):    
    notice = Notice.query.filter_by(id=notice_id).first()    
    author = User.query.filter_by(id=notice.id_user).first()
    try:
        username = current_user.username
        user = {"username": username, "writer": username in ESCRITORES}
    except:
        user = ''

    object = {
        "user": user,
        "notice": notice,
        "author": author
    }

    return render_template('show_notice.html', object=object)    

def delete(notice_id):
    notice = Notice.query.filter_by(id=notice_id).first()
    db.session.delete(notice)
    db.session.commit()    
    return redirect(url_for('index'))

controllers/UserController.py
import sys
from flask import render_template, redirect, url_for, request, abort, Flask
from flask.helpers import flash
from models import User
from flask_login import login_user, login_required, current_user, logout_user
from flask_sqlalchemy import SQLAlchemy
app = Flask(__name__)
app.config.from_object(Config)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

def store():    
    form = request.form
    username = form['username']
    password = form['password']      

    user = User.query.filter_by(username=username).first()

    if user:
        if user.password == password:
            login_user(user, remember=False)
            return redirect(url_for('index'))
        else:            
            return redirect(url_for('login'))         
    user = User(username=username, password=password)

    db.session.add(user)
    db.session.commit()

    login_user(user, remember=False)
    return redirect(url_for('index'))

@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


def show(userId):
    pass


def update(userId):
    pass


def delete(userId):
    pass

routes/notice_bp.py
from flask import Blueprint

from controllers.NoticeController import store, show, delete

notice_bp = Blueprint('notice_bp', __name__)
notice_bp.route('/create', methods=['POST', 'GET'])(store)
notice_bp.route('/<int:notice_id>', methods=['GET'])(show)
notice_bp.route('/delete/<int:notice_id>', methods=['GET'])(delete)

routes/user_bp.py
from flask import Blueprint

from controllers.UserController import store, show, update, delete, logout

user_bp = Blueprint('user_bp', __name__)
user_bp.route('/create', methods=['POST'])(store)
user_bp.route('/<int:user_id>', methods=['GET'])(show)
user_bp.route('/<int:user_id>/edit', methods=['POST'])(update)
user_bp.route('/<int:user_id>', methods=['DELETE'])(delete)
user_bp.route('/logout', methods=['GET'])(logout)

templates/create_notice.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="icon" href="{{url_for('static', filename='images/logo_nows.png')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/create_notice.css')}}">
    <title>Nows!</title>

</head>

<body>
    <div class="navbar-fixed">
        <nav>               
            <a href="{{url_for('index')}}">
                <img src="{{url_for('static', filename='images/logo_nows.png')}}" alt="logo hide-on-med-and-down">
            </a>
            <ul class="right hide-on-med-and-down">                    
                {% if user %}
                    <li>{{user.name}}</li>
                    {% if user.writer %}
                        <li><a href="{{url_for('notice_bp.store')}}">Escrever Post</a></li>
                    {% endif %}
                        <li><a href="{{url_for('user_bp.logout')}}">Logout</a></li>
                {% else %}
                    <li><a href="{{url_for('login')}}">Entrar</a></li>
                {% endif %}
            </ul>            
        </nav>
    </div>
    <div class="form-group">
        <form class="col s12 form" action="{{url_for('notice_bp.store')}}" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="input-field col s6">
                    <label for="title">Título</label>
                    <input placeholder="Título" id="title" name="title" type="text" class="validate">
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label for="subtitle">Subtitulo</label>
                    <input id="subtitle" type="text" name="subtitle" class="validate" placeholder="Subtitulo">
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label for="image">Link da Imagem de Capa</label>
                    <input id="image" type="text" name="image" class="validate" placeholder="Link da Imagem de Capa">
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label for="text">Texto</label>
                    <input id="text" type="text" name="text" class="validate" placeholder="Texto">
                </div>
            </div>                
            <div class="row">
                <input class="btn waves-effect waves-light" type="submit" value="Criar">            
            </div>                    
        </form>    
    </div>

</body>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{{url_for('static', filename='javascript/carousel.js')}}" type="module"></script>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/index.css')}}">
    <link rel="icon" href="{{url_for('static', filename='images/logo_nows.png')}}">
    <title>Nows!</title>

</head>

<body>
    <div class="navbar-fixed">
        <nav>               
            <a href="{{url_for('index')}}">
                <img src="{{url_for('static', filename='images/logo_nows.png')}}" class="logo hide-on-med-and-down">
            </a>
            <ul class="right hide-on-med-and-down">                    
                {% if object.user %}
                    <li>{{object.user.name}}</li>
                    {% if object.user.writer %}
                        <li><a href="{{url_for('notice_bp.store')}}">Escrever Post</a></li>
                    {% endif %}
                        <li><a href="{{url_for('user_bp.logout')}}">Logout</a></li>
                {% else %}
                    <li><a href="{{url_for('login')}}">Entrar</a></li>
                {% endif %}
            </ul>            
        </nav>
    </div>

    <div class="noticias">
        {% for notice in object.notices %}            
            <div class="card">
                <div class="card-image">
                    <img src="{{notice.image}}">
                </div>
                <div class="card-content">
                    <span class="card-title">{{notice.title}}</span>
                    <p>{{notice.subtitle}}</p>
                    <p>{{notice.date}}</p>
                </div>
                <div class="card-action">
                    <a href="{{url_for('notice_bp.show', notice_id=notice.id)}}">Read</a>                
                    {% if object.user.id == notice.id_user%}                        
                        <a href="{{url_for('notice_bp.delete', notice_id=notice.id)}}"><img src="{{url_for('static', filename='images/bin.png')}}" alt="lixeira"></a>                        
                    {% endif %}
                </div>
            </div>            
        {% endfor %}
    </div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/login.css')}}">
    <title>Nows!</title>

</head>

<body>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="{{url_for('index')}}" class="brand-logo"><img src="{{url_for('static', filename='images/logo_nows.png')}}"
                        alt="logo"></a>
            </div>
        </nav>
    </div>

    <div class="form-group">
        <form class="col s12 form" action="{{url_for('user_bp.store')}}" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="Nome de Usuário" id="username" name="username" type="text" class="validate">
                    <label for="username">Username</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <input id="password" type="password" name="password" class="validate" placeholder="Senha">
                    <label for="password">Senha</label>
                </div>
            </div>
            <div class="row">
                <input class="btn waves-effect waves-light" type="submit" value="Entrar">            
            </div>
        </div>
    </form>
    </div>

</body>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{{url_for('static', filename='javascript/carousel.js')}}" type="module"></script>

</html>

templates/show_notice.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/show_notice.css')}}">
    <link rel="icon" href="{{url_for('static', filename='images/logo_nows.png')}}">
    <title>Nows!</title>

</head>

<body>
    <div class="navbar-fixed">
        <nav>               
            <a href="{{url_for('index')}}">
                <img src="{{url_for('static', filename='images/logo_nows.png')}}" alt="logo hide-on-med-and-down">
            </a>
            <ul class="right hide-on-med-and-down">                    
                {% if object.user %}
                    <li>{{object.user.name}}</li>
                    {% if object.user.writer %}
                        <li><a href="{{url_for('notice_bp.store')}}">Escrever Post</a></li>
                    {% endif %}
                        <li><a href="{{url_for('user_bp.logout')}}">Logout</a></li>
                {% else %}
                    <li><a href="{{url_for('login')}}">Entrar</a></li>
                {% endif %}
            </ul>            
        </nav>
    </div>

    <main>
        <h1>{{object.notice.title}}</h1> 
        <div class="autor-data">
            <h5>{{object.author.username}}</h2>
            <h5>{{object.notice.date}}</h5>
        </div>       
        <img src="{{object.notice.image}}" alt="imagem de capa">
        <h5>{{object.notice.subtitle}}</h5>
        <div class="text">
            <p>
                {{object.notice.text}}
            </p>
        </div>
    </main>

</body>

</html>